### ISSUE TITLE
Zabbix version dependency

### ISSUE THREAD

**Issue by tpd001** [B4ckF0rw4rd/Zabbix-Templates#2]
Thanks for working on this.  However, I am encountering issues importing the ASA firewall template into 2.2.  In one instance, the 'or' operator is used in a trigger; this operator was not introduced until 2.4.
If a dependency exists on 2.4 it might be useful to modify the 'tested against' statement in the README to reflect that.

**Comment by B4ckF0rw4rd** [comment]
Hi Tim,

No there's no dependency, the problem is that when i've upgraded my zabbix
to 2.4 I've also extracted the templates overriding the originals based on
2.2.

Unfortunately I don't have backups so I'll change the minimal version to
2.4 until I figure out how to make it backward compatible.

The problem is also present in the other template of mine.

Sorry for the troubles to you all guys, I'll fix it as soon as possible.

Regards,
Manuel Mannello
Il 05/gen/2016 17:54, "Tim Donahue" <notifications@github.com> ha scritto:

**Comment by tpd001** [comment]
Thanks for getting back to me.  Your explanation makes perfect sense.  
I've made it work by:

* Removing the filter expression
* Changing <> to #
* Changing 'or' or |
* Changing 'and' to &

all in the raw XML.

The updated file is attached.

Best,
Tim

**Comment by B4ckF0rw4rd** [comment]
Hi Tim, sorry for late reply but i can't see the attachment. Anyway i'll try to edit it by myself and if it works i'll update your solution here.

Thanks for your help.
