### ISSUE TITLE
VPN items are showen as "Not supported"

### ISSUE THREAD

**Issue by rabin-io** [B4ckF0rw4rd/Zabbix-Templates#6]
I'm getting message that the following items are "Not supported"

```
Active IPSEC VPNs RemoteAccess    crasIPSecNumSessions
Active SSL VPNs RemoteAccess      crasSVCNumSessions     
Active VPNs Lan-To-Lan            crasL2LNumSessions     
```

when clicking the X mark i see this message 

```
snmp_parse_oid(): cannot parse OID "CISCO-REMOTE-ACCESS-MONITOR-MIB::crasIPSecNumSessions.0".
```

but when i run `snmpwalk` on the how with the above mib key it works,

```
$ snmpwalk -On -c wuciwug -v2c OfficeASA CISCO-REMOTE-ACCESS-MONITOR-MIB::crasIPSecNumSessions.0 

.1.3.6.1.4.1.9.9.392.1.3.26.0 = Gauge32: 2 Sessions
```

And when i replace the mib and use the numeric one the pull is working.

**Comment by B4ckF0rw4rd** [comment]
Hi, very strange, i use this template on some Zabbix and its working.

Wich zabbix version do you have? Where are your Mibs?

**Comment by rabin-io** [comment]
I'm using Zabbix version 3.0 , I also opened a ticket @ https://support.zabbix.com/browse/ZBX-9417

**Comment by B4ckF0rw4rd** [comment]
Hi, sorry for the late reply!

Where do you have the MIB files? Maybe snmpwalk and zabbix don't use the same path.

If i remember correctly, my mibs are in this path /usr/local/share/mibs

**Comment by rabin-io** [comment]
Hello, 
My mibs are in the following folders, 
```
# find / -type d -name mibs
/usr/local/share/snmp/mibs
/usr/share/mibs
/usr/share/snmp/mibs
/var/lib/mibs
```
I'm running ubuntu 14.04 and using `snmp-mibs-downloader` to auto downloads the mib files.

**Comment by B4ckF0rw4rd** [comment]
Hi, the MIBs that uses the template are not standard, are Cisco proprietary
MIBs.

Here the link for all Cisco MIBs:

ftp://ftp.cisco.com/pub/mibs/v2/v2.tar.gz

- Download it
- Extract all in /usr/local/share/snmp/mibs
- to be sure check the permissions after the extraction.


Il 10 dic 2016 6:27 PM, "rabin-io" <notifications@github.com> ha scritto:

Hello,
My mibs are in the following folders,

# find / -type d -name mibs
/usr/local/share/snmp/mibs
/usr/share/mibs
/usr/share/snmp/mibs
/var/lib/mibs

I'm running ubuntu 14.04 and using snmp-mibs-downloader to auto downloads
the mib files.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/B4ckF0rw4rd/Zabbix-Templates/issues/6#issuecomment-266224401>,
or mute the thread

**Comment by rabin-io** [comment]
I all ready had those mibs in the `/usr/local/share/snmp/mibs` folder

**Comment by B4ckF0rw4rd** [comment]
Try to do an snmpwalk with the same mib as the template.

The error that you have is realted to that, zabbix can't find the mib so it
can't discover the value and it gives you unsupported, it isn't a template
problem.

Il 11 dic 2016 11:43 AM, "rabin-io" <notifications@github.com> ha scritto:

**Comment by rabin-io** [comment]
OK, you can close this. I have open a bug report on Zabbix issue tracker as well.
