### ISSUE TITLE
Zabbix Cisco ASA 5512X

### ISSUE THREAD

**Issue by bruce1949** [B4ckF0rw4rd/Zabbix-Templates#8]
Hello,
  You are so nice that shared the templates for us so that we can use it more smoothly.
I imported the ASA template that you shared and I also create a new expressions.
![default](https://user-images.githubusercontent.com/10904633/27534442-96ccffba-5a99-11e7-91e5-ab532c07c9a4.png)
I also remote @ based on your documentation. But I can't find any grapf about the traffic and there is no data.
![default](https://user-images.githubusercontent.com/10904633/27534513-cd0f6dd8-5a99-11e7-8764-8134fd2b09a3.png)
Did I miss something?

Thanks in advance.

**Comment by B4ckF0rw4rd** [comment]
Hello,

Have you imported the Cisco MIBs? All the template uses MIBs instead of
OIDs, the easy way is to download all the cisco mib v2 from cisco FTP repo
and extract them in your machine mib folder.

On centos usually is /usr/local/share/snmp/mibs

Hello,
You are so nice that shared the templates for us so that we can use it more
smoothly.
I imported the ASA template that you shared and I also create a new
expressions.
[image: default]
<https://user-images.githubusercontent.com/10904633/27534442-96ccffba-5a99-11e7-91e5-ab532c07c9a4.png>
I also remote @ based on your documentation. But I can't find any grapf
about the traffic and there is no data.
[image: default]
<https://user-images.githubusercontent.com/10904633/27534513-cd0f6dd8-5a99-11e7-8764-8134fd2b09a3.png>
Did I miss something?

Thanks in advance.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/B4ckF0rw4rd/Zabbix-Templates/issues/8>, or mute the
thread

**Comment by bruce1949** [comment]
Absolutely, I download all the MIBs from Cisco FTP server and import it on my CentOS server. Other function are working well except: Traffic and VPN Tunnel DecryptFails

![default](https://user-images.githubusercontent.com/10904633/27567101-270e3bac-5b1c-11e7-8b69-b9d9b07bf503.png)

![default](https://user-images.githubusercontent.com/10904633/27567130-5a588d64-5b1c-11e7-912f-a3162e9e90af.png)

**Comment by B4ckF0rw4rd** [comment]
Mmmmmh the problem is related to the "not supported" things, the 2
possibile causes could be:

- cisco changed the mib related to that value
Or
- zabbix server doesn't read all your mibs

If you do an snmpwalk from the same user as zabbix process with the mib
inside those checks, does it work?

Manuel

Absolutely, I download all the MIBs from Cisco FTP server and import it on
my CentOS server. Other function are working well except: Traffic and VPN
Tunnel DecryptFails

[image: default]
<https://user-images.githubusercontent.com/10904633/27567101-270e3bac-5b1c-11e7-8b69-b9d9b07bf503.png>

[image: default]
<https://user-images.githubusercontent.com/10904633/27567130-5a588d64-5b1c-11e7-912f-a3162e9e90af.png>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/B4ckF0rw4rd/Zabbix-Templates/issues/8#issuecomment-311228202>,
or mute the thread

**Comment by bruce1949** [comment]
I check the MIB value on Cisco Website and found that it doesn't change:

![default](https://user-images.githubusercontent.com/10904633/27619726-27adf4fe-5bf7-11e7-9f35-94e185c55f0f.png)

I run the comman on my Zabbix server with root and it also has the output:

![default](https://user-images.githubusercontent.com/10904633/27619806-9cc84366-5bf7-11e7-9022-d988c4dd4a42.png)


I load all the Mibs that under /usr/shar/snmp/mibs, including third part mibs.  "mib +ALL" is added at the bottom of /etc/snmp/snmpd.conf to make sure all the mibs files are loaded.

**Comment by bruce1949** [comment]
I can't get any data about traffic either and not sure what happed.

**Comment by B4ckF0rw4rd** [comment]
So strange,

Try to put the mibs in this path /usr/local/share/snmp/mibs, if it doesn't
work the last chance is to try the oid directly in the template and than
verify it.

Another question, what is the version of the zabbix?

I can't get any data about traffic either and not sure what happed.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/B4ckF0rw4rd/Zabbix-Templates/issues/8#issuecomment-311549285>,
or mute the thread

**Comment by bruce1949** [comment]
Thank you all the same. I tried any opinions that you mentioned without lucky. I will try later

Sent from my iPhone

On 29 Jun 2017, at 04:21, Manuel Mannello <notifications@github.com<mailto:notifications@github.com>> wrote:

So strange,

Try to put the mibs in this path /usr/local/share/snmp/mibs, if it doesn't
work the last chance is to try the oid directly in the template and than
verify it.

Another question, what is the version of the zabbix?

I can't get any data about traffic either and not sure what happed.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/B4ckF0rw4rd/Zabbix-Templates/issues/8#issuecomment-311549285>,
or mute the thread

**Comment by B4ckF0rw4rd** [comment]
Do the template get the interfaces?

**Comment by bruce1949** [comment]
No， I don't know what happened, I can get the interface with snmpwalk command line, but there's no output with the template that I imported. Zabbix version: 3.09

Sent from my iPhone

On 29 Jun 2017, at 20:25, Manuel Mannello <notifications@github.com<mailto:notifications@github.com>> wrote:


Do the template get the interfaces?

**Comment by B4ckF0rw4rd** [comment]
I don't have any more ideas, it's not a template issue, i've many feedbacks
that it works on v3.0 and also v3.2.

It's something related to MIBs-Zabbix communication. If you can't find the
problem, the last chance is to convert all the MIB parts on the template to
OIDs.

Regards,
Manuel
