### ISSUE TITLE
Zabbix 3 Cisco ASA 5510

### ISSUE THREAD

**Issue by msmarziali** [B4ckF0rw4rd/Zabbix-Templates#9]
Hi,

In my zabbix server (3.2.5) i uploaded the template "Template Cisco ASA Discoveryv3.xml".
![template_imported](https://user-images.githubusercontent.com/2008688/27642673-ce6007a6-5c1f-11e7-9d6a-ec39ca5baa13.jpg)

I setup in my cisco asa the snmp configuration:
![snmp_configuration_asa](https://user-images.githubusercontent.com/2008688/27642579-81269bd0-5c1f-11e7-82aa-fcaa05b16824.jpg)

I have created the host that has the ip firewall address as: 
![host_asa](https://user-images.githubusercontent.com/2008688/27642864-5856d278-5c20-11e7-9c06-e3765e9497f9.jpg)

When I go to the template I get the following error
![error](https://user-images.githubusercontent.com/2008688/27642906-74c479ce-5c20-11e7-87aa-5a80b092e7b5.jpg)

In  my zabbix sever i have installed Mibs cisco for ASA.
![mibs_installate](https://user-images.githubusercontent.com/2008688/27643230-bfa62eba-5c20-11e7-9d23-76604d33bae5.jpg)

The command snmpwalk -v 2c -c community 10.2.0.253 work.
![snmpwalk](https://user-images.githubusercontent.com/2008688/27643375-26bc7b0e-5c21-11e7-8e81-74b576472194.jpg)

Can you give me directions, I'm wrong all? 
Thanks for the time dedicated to me

Regards,
Massimiliano.

**Comment by B4ckF0rw4rd** [comment]
Ciao Massimiliano,

L'errore che da non dice gran che, l'errore te lo da appena linki il
template all'host?

Hai creato il la regexp per le interfacce? Va creata prima di
importare/legare il template.

Riguardo ai mibs, per sicurezza assicurati di averli anche in questo path
/usr/local/share/snmp/mibs.

Hi,

In my zabbix server (3.2.5) i uploaded the template "Template Cisco ASA
Discoveryv3.xml".
[image: template_imported]
<https://user-images.githubusercontent.com/2008688/27642673-ce6007a6-5c1f-11e7-9d6a-ec39ca5baa13.jpg>

I setup in my cisco asa the snmp configuration:
[image: snmp_configuration_asa]
<https://user-images.githubusercontent.com/2008688/27642579-81269bd0-5c1f-11e7-82aa-fcaa05b16824.jpg>

I have created the host that has the ip firewall address as:
[image: host_asa]
<https://user-images.githubusercontent.com/2008688/27642864-5856d278-5c20-11e7-9c06-e3765e9497f9.jpg>

When I go to the template I get the following error
[image: error]
<https://user-images.githubusercontent.com/2008688/27642906-74c479ce-5c20-11e7-87aa-5a80b092e7b5.jpg>

In my zabbix sever i have installed Mibs cisco for ASA.
[image: mibs_installate]
<https://user-images.githubusercontent.com/2008688/27643230-bfa62eba-5c20-11e7-9d23-76604d33bae5.jpg>

The command snmpwalk -v 2c -c community 10.2.0.253 work.
[image: snmpwalk]
<https://user-images.githubusercontent.com/2008688/27643375-26bc7b0e-5c21-11e7-8e81-74b576472194.jpg>

Can you give me directions, I'm wrong all?
Thanks for the time dedicated to me

Regards,
Massimiliano.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/B4ckF0rw4rd/Zabbix-Templates/issues/9>, or mute the
thread

**Comment by msmarziali** [comment]
Ciao,

l'errore me lo da appena prova a linkare il template all'host.
**Per quanto riguarda la regexp per le interfacce, non l'ho creata. Come dovrei crearla ? (E' poco che uso zabbix).**

Per quanto riguarda le mibs, ho provveduto a creare il path /usr/local/share/snmp/mibs ed a copiare le mibs che avevo già sotto /usr/share/snmp/mibs.

Il server Zabbix è Centos 7: CentOS Linux release 7.3.1611 (Core)

Grazie del tempo dedicatomi.

Massimiliano.

**Comment by B4ckF0rw4rd** [comment]
Ciao Massimo,

la regexp va creata prima, sul come creare una regexp guarda quì (Global regular expression): 

https://www.zabbix.com/documentation/3.2/manual/regular_expressions

Per la regexp specifica che ti serve ci sono i dettagli nel readme.

Manuel

**Comment by msmarziali** [comment]
Ciao,

ho creato la regexp e cercato poi di associare il template all'host, ma ottengo sempre lo stesso errore.

![regexp](https://user-images.githubusercontent.com/2008688/27698389-401fc502-5cf7-11e7-9756-653d28f3902a.jpg)


Grazie,
Massimiliano.

**Comment by B4ckF0rw4rd** [comment]
Prova a ricaricare il template ora che hai sistemato la regexp e poi
linkalo.

Se da ancora errore l'unica cosa che mi viene in mente è che abbiano
cambiato qualcosa nella 3.2

Manuel

**Comment by msmarziali** [comment]
Ciao Manuel,

sono riuscito a trovare l'errore e a caricare il template.
L'errore era che nella definizione dell'host avevo configurato l'ip sulla sezione agent e no snmp.

Ho creato l'host e associato il template con la regexp.
E' normale che alcune voci appaiano disabilitate e per altre non ho dati ?!
![cisco_asa](https://user-images.githubusercontent.com/2008688/27740361-0d9f9e84-5db2-11e7-8910-1d8a0ce32dfa.jpg)

Grazie ancora del prezioso supporto.
Massimiliano.

**Comment by B4ckF0rw4rd** [comment]
Ahhhhh ok, a posto.

Si è normale all'inizio, lascialo girare una giornata almeno (ci vuole
tempo prima che popoli tutto).

Chiudi pure l'issue.

Ciao e grazie,
Manuel

**Comment by msmarziali** [comment]
Grazie Manuel.

Saluti.
Massimiliano.
